development:
  adapter: postgresql
  encoding: unicode
  database: twittercoin_development
  pool: 5
  username: twittercoin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twittercoin_test
  pool: 5
  username: twittercoin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: twittercoin_production
  pool: 5
  username: twittercoin
  password:
